### ISSUE TITLE
Project not allowing pnpm 9

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#1007]
## Description
- With pnpm 9's release, the latest version doesn't pass the dependency check (pnpm ^8.0.0) because this doesn't cross major version barriers.
- I've tried to change the requirement to the latest version, which works with no further changes. We just need to put this into a PR.

**Comment by laggycomputer** [comment]
One could check [here](https://github.com/pnpm/pnpm/releases/tag/v9.0.0-rc.0) for any changes, but a package manager change shouldn't break anything except for invalidating lockfiles and making previous installations maybe a bit more hairy to update.
