### ISSUE TITLE
Duplicate custom events when exporting to ics

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#1010]
## Description
- When a custom event with multiple days is exported in an `ics` file, multiple copies of it are created.
- Below is the relevant excerpt from an exported file containing one custom event repeating on Sunday and Monday. 
```
SUMMARY:
DTSTAMP:20241002T004655Z
DTSTART;TZID=America/Los_Angeles:20240929T103000
DTEND;TZID=America/Los_Angeles:20240929T153000
RRULE:FREQ=WEEKLY;BYDAY=SU,MO;INTERVAL=1;COUNT=20
END:VEVENT
BEGIN:VEVENT
UID:5ZX0Zax9m6HBFzZzDHfbZ
SUMMARY:
DTSTAMP:20241002T004655Z
DTSTART;TZID=America/Los_Angeles:20240929T103000
DTEND;TZID=America/Los_Angeles:20240929T153000
RRULE:FREQ=WEEKLY;BYDAY=SU,MO;INTERVAL=1;COUNT=20
```

## Reproduction
- Create a custom event repeating on multiple days.
- Download the `ics` file.
- Inspect it manually or import it into a calendar app.

## Diagnosis
- It's probably to do with how multiple events are created for class sections that meet multiple times.
    - I think this is the case because class sections can meet in different places throughout the week.
- The fix likely involves either creating only one event repeating on multiple days for custom events (preferable) or creating one custom event for each day.

**Comment by vinnyho** [comment]
Could I take this problem?
