### ISSUE TITLE
download .ics file not working

### ISSUE THREAD

**Issue by winbrrr** [icssc/AntAlmanac#1016]
I cannot download the .ics file to import into my Google Calendar. The button gives visual feedback that it's been clicked but no download begins. I tried disabling adblock, using a different browser, and even using a different computer/phone but it did not work in any case. 

Downloading the screenshot works fine, it's just the .ics file that doesn't work.

**Comment by IanWearsHat** [comment]
When clicking the download icon, this error shows up in the console.
![image](https://github.com/user-attachments/assets/5e1652af-b8f3-4c09-a639-a14d0f7cc0db)

I looked in the `apps/antalmanac/src/lib/download.ts` file and found that the error occurs here:
![image](https://github.com/user-attachments/assets/5eef9879-0f19-4af1-b17f-4beafcb93f94)

It looks like the error occurs for custom events in the schedule that don't have a location. Specifically, the `.name` attribute doesn't exist in the object. If all custom events have a location, the error does not occur.
