### ISSUE TITLE
Create Privacy Policy

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#108]
We'll need to mention what information we're storing (course codes, schedule names, etc.) and what information we are tracking (Google Analytics).

Google Analytics might provide specific language for us to include in our privacy policy.

**Comment by MinhxNguyen7** [comment]
I'm working on this now. Here's the [working document](https://docs.google.com/document/d/1cSWlwNrVh-fRGowT8oysjfZ1ansPLoVifrfsq1YZ0Vg/edit?usp=sharing). DM me if anyone wants access.

**Comment by MinhxNguyen7** [comment]
Privacy policy draft is done
