### ISSUE TITLE
Remove all inline styles and use the Material UI standard CSS-in-JS solution using withStyles.

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc/AntAlmanac#122]
There are many instances where we used inline styles for debug/prototyping (and out of carelessness) that we can move to use the standard. This will allow us to easily inject global styles (better dark mode support) and also manage styles at a glance easily.

**Comment by ChaseC99** [comment]
`@fellowship students`
Multiple people can work on this task. Please comment which file(s) you are going to work on.

**Comment by EricPedley** [comment]
Not super important, closing this to clean up issue queue.
