### ISSUE TITLE
Maps: Customize the popup with compliant design

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc/AntAlmanac#127]
![image](https://user-images.githubusercontent.com/30539874/86566530-acf6c900-bf1e-11ea-949f-079be93e14b9.png) is the current layout. We should come up with a more compliant and aesthetic design for this.

Design needs to integrate an image carousel since multiple images are available in buildingCatalogue.js now.

**Comment by KevinWu098** [comment]
This DaUCI design from 2021 would be a great starting point (if not endpoint) for redesigning the Map popup 

<img width="374" alt="Screenshot 2023-10-12 at 10 24 07 AM" src="https://github.com/icssc/AntAlmanac/assets/100006999/c7add7e3-f31c-4f55-9ef6-fbb082ef888a">

https://www.figma.com/file/sD5kOcQmDdPdHE2GQaXL1h/Antalmanac?type=design&node-id=572%3A1401&mode=design&t=7lNWw0w8LoAe42Mu-1
