### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc/AntAlmanac#129]

**Comment by devsdevsdevs** [comment]
On every network request, make sure that there's a try-catch and error message etc.

**Comment by EricPedley** [comment]
Pretty sure we're good here, but we should test everything before closing this. None of these should crash the site:

- [ ] failed websoc request
- [ ] failed map api request
- [ ] failed schedule load request

**Comment by MinhxNguyen7** [comment]
I'm pretty sure the page will be OK.
