### ISSUE TITLE
About Module

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#130]
- [x] Add "About" button to navbar
- [x] Create a popup module (similar to the notifications one but bigger) for information about the project.

Information to include
- How we're maintained by ICSSC Projects
- Link to Discord (discord.gg/GzF76D7UhY)
- Link to GitHub

**Comment by ChaseC99** [comment]
I'll get you more specific info for the About module later. For now, feel free to put dummy text and just get the functionality of the popup working.

**Comment by EricPedley** [comment]
Ok, I made a popup with dummy text at the [about-page branch]( https://github.com/icssc-projects/AntAlmanac/tree/about-page).
![image](https://user-images.githubusercontent.com/48658337/149830645-fd453148-79b8-465d-a2f4-94c80705bfd2.png)
 LMK what the next steps are.

**Comment by ChaseC99** [comment]
> AntAlmanac is a schedule planning tool for UCI students. 
> 
> The website is maintained by the [ICS Student Council](https://studentcouncil.ics.uci.edu) Projects Committee.
> 
> Interested in helping out? Join our [Discord](https://discord.gg/GzF76D7UhY) or checkout the [code on GitHub](https://github.com/icssc-projects/AntAlmanac).
