### ISSUE TITLE
Add Zotistics links for grade distribution

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc/AntAlmanac#132]
Endpoint format: https://zotistics.com/?teacher=PATTIS+R.&selectQuarter=Fall&selectYear=2020-21&selectDep=All+Departments&classNum=&code=&submit=Submit

**Comment by devsdevsdevs** [comment]
For now: Linking to Zotistics using the endpoint
We can go two routes: An embed of the graph a la ZotCourse or use PeterPortal API to display our own bar graph.

**Comment by devsdevsdevs** [comment]
Only need to populate the selectDep and classNum fields

**Comment by ileenf** [comment]
Note: url doesn't work without selectQuarter and selectYear queries, selectDep is Computer+Science instead of COMPSCI
