### ISSUE TITLE
Implement SectionTable with material-ui table

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc/AntAlmanac#133]
- [x] Change vanilla HTML components to Material UI components
- [x] Give each cell max-width so that every table aligns nicely
- [x] Change text and section type colors so that they look good with dark mode
- [ ] See if we can optimize mounting of various modals etc (also avoid having every single table listen to the Flux store which warns as a memory leak)

**Comment by devsdevsdevs** [comment]
Nice work on getting this started @kartik-bhagatwala, I'm now working on making this ready for prod, gotta fix mostly CSS stuff first, but will also see if we can optimize the rendering speed and also clean up the code.

**Comment by EricPedley** [comment]
I think this should be safe to close.
1. 3/4 of the points are already done
2. "See if we can optimize mounting of various modals etc" is too vague to be actionable anymore
3. I checked with Firefox memory profiler, and the listeners actually do seem to contribute a lot to our site's memory usage, but I think it deserves its own issue.
