### ISSUE TITLE
Download ICS: refactor to use calendarize helper

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#147]
ExportCalendar uses AppStore's getAddedCourse instead of getEventsInCalendar, because getEventsInCalendar was missing critical information.

- [x] Determine what info was missing from getEventsInCalendar (I forgot already 😅)
- [x] Refactor the calendarize function to include the necessary info
- [x] Refactor ExportCalendar to use getEventsInCalendar

**Comment by JacE070** [comment]
I'm going to get this done by Oct. 26 (3 weeks)

Update: Might be done 1 week earlier. By Oct. 19.

Update: Gotta get it back to the original delivery day : )

**Comment by JacE070** [comment]
### Analysis of Current Functions
AppStore.getEventsInCalendar returns both getCurrentCourses and getCurrentCustomEvents.

What we extract and use from Appstore.getCurrentCourses:
`{
term,
deptCode,
courseNumber,
courseTitle,
section: { sectionType, instructors, meetings, finalExam },
}`

`meetings: array(WebsocSectionMeeting) {
timeIsTBA,
bldg,
days,
startTime,
endTime
}`

What we get from AppStore.calendarizeCourseEvents:
`{
color,
term,
title,
courseTitle
locations,
showLocationInfo,
instructors,
sectionCode,
sectionType,
start,
end,
finalExam,
isCustomEvent
}`

What we get from AppStore.calendarizeCustomEvents:
`{
customEventID,
color,
start,
isCustomEvent,
end,
title
}`

### What's Missing?

#### AppStore.calendarizeCourseEvents
- deptCode
- days

#### AppStore.calendarizeCustomEvents
- days
- bldg (feature is under review)
- term

**Comment by JacE070** [comment]
Where to retrieve the **term** for customEvent? Looks like **term** is not defined in RepeatingCustomEvent, which means we don't know the start and end date.

**Comment by JacE070** [comment]
Then comes a problem: do we want users to export their custom event schedule?
