### ISSUE TITLE
Dark Mode Improvements

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#155]
- [x] Schedule of classes improvements 
![image](https://user-images.githubusercontent.com/29494270/116827554-5c57f880-ab4e-11eb-9690-3556f591f033.png)
- [x] Tool tip link visibility 
![image](https://user-images.githubusercontent.com/29494270/116827567-70035f00-ab4e-11eb-94d8-d4415149f0cf.png)
- [x] Loading video

**Comment by devsdevsdevs** [comment]
Goes hand in hand with #133 btw
