### ISSUE TITLE
Bug with added courses deletion

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc/AntAlmanac#164]
Bug where deleting a course from added courses does not remove the course from the added courses pane, but when another course is removed, the added courses pane is back in sync. Possibly a desync/rerender issue. Hasn't been recreated yet.

**Comment by ChaseC99** [comment]
Adding a `low` label until we can reproduce

**Comment by ChaseC99** [comment]
Closing unless until we can reproduce.
