### ISSUE TITLE
Once PeterPortal API implements past enrollment data, uncomment the graph modal

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#182]
AntAlmanac used to store past enrollment data and display it in a modal in the EnrollmentGraph component, rendered inside SectionTable. We removed this feature from our API and requested that PeterPortal API implements it (https://github.com/icssc/peterportal-public-api/issues/111). Once they finish, we should put the modal back but still keep the link to ZotTracker.
Reasoning behind moving the data to PeterPortal:
- Provides this information for all student developers to use
- Logically it makes sense for PeterPortal API to collect and serve all UCI related data. 
- It will fit nicely into their larger data pipeline plans.

**Comment by EricPedley** [comment]
We already did this, right? Safe to close?

**Comment by ChaseC99** [comment]
We've removed the enrollment data from AntAlmanac but it's not setup on the API yet. You can close this if there's another issue to add the enrollment modal back once it's up on the API

**Comment by EricPedley** [comment]
So what this issue is talking about is the past enrollment data that used to be stored by us and available in a modal but is now just a link to ZotTracker? Do we have an issue open in PeterPortal API for this?

**Comment by ChaseC99** [comment]
Correct. Ideally we bring the modal back and add a "View more on ZotTracker" link on the bottom like how we have with grades. 

Here's the API Issue for this task: https://github.com/icssc/peterportal-public-api/issues/111

**Comment by EricPedley** [comment]
Ok I edited the description of this issue

**Comment by EricPedley** [comment]
@ecxyzzy when do you think this feature would be ready on the API?
