### ISSUE TITLE
Improve developer onboarding experience

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#183]
Goals:

- [x] Setting up and running AntAlmanac should be an extremely easy and fast process for new developers. 
- [x] Any developer should be able to run the project and work on the frontend without the backend .env file. 
- [x] Documentation should be publicly available

Know Issues:
- Backend server fails and throws many errors without `AA_MONGODB_URI` .env value
    - We shouldn't provide this key to everyone.
    - Should gracefully fail when missing, so terminal output doesn't become a warzone.
- Open source developers will not be able to access backend data like `news`, `loadUserData`, `users`, or `banners`.
    - These endpoints aren't necessary for most frontend development. However It may be annoying that they cannot save a schedule for local dev though.
    - For now, won't fix
- Open source developers can't access informational endpoints like `enrollmentData` and `websocapi`
    - This data can come from the PeterPortal API (#181 and #182)
- Notion pages are not publicly available

Other potential areas of improvement:

- [x] Simplify npm commands to install and run the project
- [ ] Create a `/scripts` directory so we can have better start and deploy processes
- [ ] Reduce # of npm packages [?]
- [ ] Make some notion docs public

**Comment by ChaseC99** [comment]
#187 fixed an issue that prevented classes from loading due to the `/news` endpoint failing

**Comment by EricPedley** [comment]
All the known issues are fixed now, besides the notion thing. I think by now a lot of the stuff on Notion is outdated or not useful for open-source developers so I'm just gonna close this issue.
