### ISSUE TITLE
Serverless does not work locally with Node V16

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#209]
For some reason the backend doesn't work properly when running the latest version of node. When attempting to load/save schedules, request to the backend hang.

Downgrading to V12 works, but ideally the backend should be able to run on the latest version of node.

**Comment by Voark** [comment]
Seems more like the Express router not handling POST requests as opposed to serverless issues as ads still load. When saving or loading a new schedule, the POST request is just stuck with no response.
![image](https://user-images.githubusercontent.com/53128285/149641484-fae47354-d89d-4ed6-b854-16113240d202.png)

It seems like the [code](https://github.com/icssc-projects/antalmanac-backend/blob/a56ce7aa6d98caa8ca1461c023e7fffc1a155d7e/routes/users.js) that handles the request is not even called at all as no code changes I make inside the functions have any effect. 

Tested on Node 16.13.1 and cross checked on Node V12 just to see if my code changes did have an effect, which they did.

**Comment by EricPedley** [comment]
I think this actually is a serverless issue. When I just stick 
```
require('dotenv').config()
app.listen(8080,()=>console.log("running on 8080"));
```
at the end of server.js, run `npm install dotenv`, and start it with `node server.js` instead of serverless offline, it works fine on Node v16.13.2.

**Comment by ChaseC99** [comment]
cc: @devsdevsdevs 
Looping you into this convo for when we migrate away from serverless.

**Comment by ChaseC99** [comment]
Can we close this @Voark?

**Comment by Voark** [comment]
@ChaseC99 Yes, completely forgot about this issue.
