### ISSUE TITLE
Bad contrast on some items in dark mode

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#224]
It's hard to see the arrow on the back button when looking at the class search results (see screenshot below)
![image](https://user-images.githubusercontent.com/48658337/151758207-a7cceef8-343f-4730-9096-69aa315e890c.png)
My roommate was using it for the first time and couldn't figure out how to get out of that screen cause the back button doesn't look like a back button.
Maybe we might add text saying "Back" next to the button and/or change the button icon for better contrast.

**Comment by jon-pruessmeier** [comment]
Hey Eric,
I would like to work on it. Could you please assign me to it?

**Comment by jbeanz** [comment]
I can do this, can you assign me?

**Comment by ChaseC99** [comment]
Hi @jbeanz, are you a student at UC Irvine? The `good first task` issues are set aside for students who would like to learn more about web development.

**Comment by jbeanz** [comment]
> Hi @jbeanz, are you a student at UC Irvine? The `good first task` issues are set aside for students who would like to learn more about web development.

I am not unfortunately :/ Can I still work on it? I ask because I'm a student preparing for job search.

**Comment by ChaseC99** [comment]
I apologize but like I mentioned, we have these issues set aside for our students. Thank you for your interest in the project though!

**Comment by EricPedley** [comment]
Renamed issue to be more general because I also want to point out the bad contrast on the load/save popups: 
![image](https://user-images.githubusercontent.com/48658337/155476245-076a9f8e-7880-49a4-b3d2-02a67e8009d6.png)
It's dark blue text against a black background, and with a blue light filter on it's basically invisible. Maybe make those into buttons with blue backgrounds and white text?

**Comment by ChaseC99** [comment]
Adding onto this, when you hover over the Back button it goes slightly transparent and looks bad in both dark and light mode. We should change this behavior. 
<img width="103" alt="image" src="https://user-images.githubusercontent.com/29494270/158049578-c2b942a5-cd49-4318-b1ab-a99b13a966fa.png">

**Comment by akins1** [comment]
I'll take this one!

**Comment by elainelt** [comment]
I'll take this one! :)

**Comment by devsdevsdevs** [comment]
Closing since merged
