### ISSUE TITLE
Add "import from study list" feature

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#225]
For people who are migrating to antalmanac for the first time, it would be convenient to be able to copy/paste your entire study list into a form somewhere on the site and it automatically add all your classes. Like for example, you could highlight your study list like the following: 
![screenshot of study list being highlighted](https://user-images.githubusercontent.com/48658337/151759174-f32e2a45-01f8-463a-8d21-4d66a0042a4a.png)
and paste it in. The pasted text would be in this form:
```
  33226 WRITING   39B SEM   Z  4.0  GR      T T   11:00-12:20   SSL  117       
   35670 I&C SCI    51 LEC   A  6.0  GR      T T   08:00-09:20   HSLH 100A      
   35671 I&C SCI    51 DIS 1A   0.0  GR mc    W    07:00-07:50pm HSLH 100A      
   35684 I&C SCI    51 LAB A4   0.0  GR      T T   02:00-03:20   TBA  TBA       
   36010 IN4MATX    43 LEC   A  4.0  GR      T T   12:30-01:50   HIB  100       
   36012 IN4MATX    43 DIS 2    0.0  GR         F  10:00-10:50   DBH  1300      
   37180 STATS      67 LEC B    4.0  GR mc   T T   05:00-06:20pm ICS  174       
   37182 STATS      67 DIS B2   0.0  GR mc      F  04:00-04:50   ICS  180    

```

Parsing out the course codes can just be done by running a regex on 5 digit numbers in the user input.

**Comment by ChaseC99** [comment]
Ohhh I like this
