### ISSUE TITLE
Add GE fulfillments to course info bar 

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#248]
When a user clicks on a course for more info, list any GEs that it might satisfy below the prereqs.
<img width="553" alt="image" src="https://user-images.githubusercontent.com/29494270/154412417-d8d3d325-ebda-4cbf-8b6f-23b94a4cf102.png">

We already have access to this information in the REST request. You should be able to get this information off of the `ge_list` option.
<img width="560" alt="image" src="https://user-images.githubusercontent.com/29494270/154412756-f4c17f7c-96a7-4a4e-a7c1-782a8c172475.png">

**Comment by dxiuu** [comment]
ill take this

**Comment by ChaseC99** [comment]
@dxiuu 
We've made a significant change to the file structure, which should make getting setup for frontend development much easier. 

Before you make any changes, make sure to pull the latest changes into your fork by clicking on "Fetch upstream" and then "Fetch and merge"
![image](https://user-images.githubusercontent.com/29494270/158087237-974e4321-d6d2-4a2c-950b-814f8bce7639.png)

**Comment by dxiuu** [comment]
sounds good!
