### ISSUE TITLE
Add Location (Lat/Long) or building field to custom events

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#249]
User feedback request:
> It would be nice to be able to put a specific location/ building on our custom events so we can see the paths.

Let's add a field to the custom events box to add location. Maybe either a building dropdown option or input the lat/long manually. These should show up on the map too.
The info in `client/src/components/Map/static/buildingCatalogue.js` might be helpful.

**Comment by stevenguyukai** [comment]
update the code to new map. Target to complete in 10/12
