### ISSUE TITLE
Show Course Overview

### ISSUE THREAD

**Issue by tjhu** [icssc/AntAlmanac#25]
The result page for searching all class in CS is super long and it takes a long time to scroll through.
It would be nice to only show an overview of each course on the result page. And we can click on each class the expand to get a detailed description.

**Comment by the-rango** [comment]
Hey there gitletH!

Yes we have that! We call it "tile view". In the tool bar above the search results, you will find two buttons, tile view and list view. After you search, you can click on tile view and you should see something along the lines of what you described. Hmm we need to make that a toggle... and maybe more obvious.

Please let me know if this helped! Thanks for using the AntAlmanac!

**Comment by gitletH** [comment]
That's nice, didn't notice that.
It would be better if we can see some more high-level details in the tile view. Like whether a class is open, full, or waitlist.

**Comment by the-rango** [comment]
Oh yes, that's a good idea! We'll think about it! 

One of the things that we wanted to do originally, was to let people specify which data fields they want to see, when the search returns. For example, the location of the class has never been important to my scheduling decisions. As such, I would not need the location field in the search results. This would help to reduce clutter in list view.

But in any case, we are somewhat stranded between two extremes. One is all the information on one page, which makes it easy to compare (webSOC); the other is the tile view or the way courseeater has it. Quite frankly we're still figuring out how to strike a balance...

**Comment by gitletH** [comment]
Probably doing A/B testing or simply asking users for feedback might help. Looking forward to seeing this product grow!

**Comment by the-rango** [comment]
I'm gonna keep this open as a reminder to work on this.

**Comment by EricPedley** [comment]
Closing as stale. It's been 3 years since this was opened and nobody's picked this up. I don't even think tile view and list view are options anymore. The idea about filtering columns is nice but different enough for a new issue.
