### ISSUE TITLE
Support Tablet Screen Sizes

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#250]
> Another potential change we can make in the future is support for tablets that are oriented vertically. If I switch to the dimensions of an iPad Air/Mini, the page is stuck on the calendar and doesn't show the Calendar and Search tabs on the top.
> 
> ![IPadDimensions](https://user-images.githubusercontent.com/78244965/154416445-e89f631c-eabe-4072-9633-3c66320ebea5.jpg)
> 
> Otherwise, this looks good to go!

_Originally posted by @Douglas-Hong in https://github.com/icssc-projects/AntAlmanac/pull/247#pullrequestreview-885483583_

**Comment by ChaseC99** [comment]
Quick and simple solution for now could be to just make the min-width for the tab bar fit tablets as well

**Comment by EricPedley** [comment]
Marking as high priority because I just personally ran into this problem when opening the site across half my monitor, so this issue applies to any window with a certain width, not just tablets.
