### ISSUE TITLE
Classes with multiple locations show up multiple times on calendar

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#257]
User Report:
![image](https://user-images.githubusercontent.com/29494270/154628095-60906bc5-1572-43ee-8606-277255f9677f.png)

When a class has 2 locations, it creates 2 events on the calendar. Ideally it should only create one event with both locations. In this case, it seems like it would be a pretty easy `if statement` to check if the class times are the same.

This formatting can mean two different things when there are multiple days (e.g. MW)
- the class is offered at the same time in both rooms (usually the room would be conjoined)
OR
- On Monday the class is in one room and on Wednesday it’s in a different room

When fixing this we just need to make sure we don’t break .ics downloads or squash classes that are locations for different times.

**Comment by MinhxNguyen7** [comment]
This happens as a result of duplication on the API end. See the PR (#467).
