### ISSUE TITLE
Visual Bug on Course Results Page

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#260]
When the window is narrow, the icons on the course results page render outside of their buttons. We should make them stack on top of the text, or disappear, or truncate the text.
![image](https://user-images.githubusercontent.com/48658337/155464054-cc841f7d-51d0-4d6a-b958-644578cf6dbd.png)

**Comment by ChaseC99** [comment]
I feel like if we remove the icon on smaller screen sizes, that should be good.

Maybe we should also rename "Prerequisites" to "Prereqs"?

**Comment by heyitsmichellelin** [comment]
I'll take this one for the fellowship task!

**Comment by devsdevsdevs** [comment]
Closing since fix merged
