### ISSUE TITLE
Enter button should submit search form

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#261]
When the user is on the class search page, pressing the `enter` or `return` button should trigger the search
<img width="861" alt="image" src="https://user-images.githubusercontent.com/29494270/155630865-4befb6f2-d345-4e24-9f23-50914ffa216d.png">

**Comment by sravtall** [comment]
I can do this one!

**Comment by ChaseC99** [comment]
Thanks! Just so you know, there might already be code in `SearchForm.js` that tries to do this but I think it's broken.
