### ISSUE TITLE
Color picker on right side doesn't change when modified from calendar view

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#263]
Steps to reproduce:
1. add a class to schedule
2. go to added classes page
3. click on the class in the calendar view, and change its color using the color picker
4. observe that the color of the color picker on added classes doesn't change

![(alt text) the problem visualized as a gif](https://user-images.githubusercontent.com/48658337/155907541-8d0f7f52-864c-4338-ab14-651fe60793a8.gif)

**Comment by EricPedley** [comment]
Tagged for someone else to do. My thoughts for this one were to look at the calendar view (ScheduleCalendar.js) to see how it listens for color changes, and just copy that to the section table code, which is where the color picker is in (SectionTable.js, SectionTableBody.js, SectionTableButtons.js). Pro tip is to ctrl+p search for these files in VSCode instead of digging through the file structure.

**Comment by devsdevsdevs** [comment]
>  Pro tip is to ctrl+p search for these files in VSCode instead of digging through the file structure.

Or ctrl + shift + f for the Webstorm/JetBrains enjoyers

**Comment by alisa-lu** [comment]
I'll take this one

**Comment by ecxyzzy** [comment]
Closing since #326 was merged.
