### ISSUE TITLE
Update deprecated NPM packages

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#267]
There are a lot of deprecation warnings when running `npm i` for AntAlmanac. Go through these and update the packages.
<img width="1548" alt="image" src="https://user-images.githubusercontent.com/29494270/156366002-df65271c-74b8-43b4-a9f0-d9e8043ef0c5.png">

Some updates, like switching from Material UI v4 to v5, might be slightly more work. Create additional issues if needed.

- [x] #335 
- [x] #336
- [x] #334
- [x] #279

**Comment by ChaseC99** [comment]
Would you mind looking into this @ecxyzzy?

**Comment by ecxyzzy** [comment]
Sure thing—I'll go ahead and create the sub-issues for the deprecated packages that don't involve the MUI v5 migration first, since we already have #279 for that. Once those are done, if you could add those as tasks to the body of this issue that'd be great.

**Comment by ecxyzzy** [comment]
Subtasks in (approximate/subjective) ascending order of complexity:
- [ ] #335 
- [ ] #336
- [ ] #334
- [ ] #279

Edit: looks like this didn't link the issues as tasks. @ChaseC99 do you mind adding this to the issue body to see if that tracks?

**Comment by ChaseC99** [comment]
Looks like that worked!

**Comment by EricPedley** [comment]
Closing this since the child issues being open is sufficient.
