### ISSUE TITLE
In search form, rename "Search for a department" to "Department"

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#268]
"Search for a department" is too long and doesn't match the rest of the field labels. Rename it to just "Department"
![image](https://user-images.githubusercontent.com/29494270/156437269-e17baddb-5675-4c75-96cb-866783da40cc.png)

See [DeptSearchBar.js](https://github.com/icssc-projects/AntAlmanac/blob/main/client/src/components/SearchForm/DeptSearchBar/DeptSearchBar.js)

**Comment by Ykhan799** [comment]
I will take this one.
