### ISSUE TITLE
In CourseInfoBar, rename "Prerequisite For" to "Prerequisite for"

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#269]
When you click on a course's name, it displays additional information. 
The "for" in "Prerequisite For:" should not be uppercase. Make it lowercase.

![image](https://user-images.githubusercontent.com/29494270/156437942-d90d254c-7698-4124-9a0d-5c5547c1e50e.png)

**Comment by LawrenceBLu** [comment]
I can do this one!
