### ISSUE TITLE
Preselect current schedule when creating a custom event

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#271]
When we click the "Add Custom" button, this dialog box appears prompting the user to add a custom event. If we are on "Schedule 1", then the "Schedule 1" box should already be checked off. 

![image](https://user-images.githubusercontent.com/29494270/156439184-c42f75a0-f957-4f37-a7df-6f30a55a0daa.png)

**Comment by rayoh123** [comment]
I'll take this one

**Comment by ChaseC99** [comment]
@rayoh123 
We've made a significant change to the file structure, which should make getting setup for frontend development much easier. 

Before you make any changes, make sure to pull the latest changes into your fork by clicking on "Fetch upstream" and then "Fetch and merge"
![image](https://user-images.githubusercontent.com/29494270/158087237-974e4321-d6d2-4a2c-950b-814f8bce7639.png)
