### ISSUE TITLE
Make Custom Event Dialog Box wider

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#272]
The Custom Event dialog box is not wide enough. The weekdays overflow onto two lines, which looks weird. 
<img width="666" alt="image" src="https://user-images.githubusercontent.com/29494270/156547795-5f1514c0-60bd-4acc-91e9-27fb64b5d3c7.png">

Make the box wider so that the days all fit on one line. 
This should be as simple as adding `maxWidth={"lg"}` to [CustomEventDialog.js#L121](https://github.com/icssc-projects/AntAlmanac/blob/5195b20bb8ab452f65d0c259c00f63ce9f8b032d/client/src/components/CustomEvents/CustomEventDialog.js#L121)
```jsx
<Dialog open={this.state.open} maxWidth={"lg"}>
```

**Comment by TanushGo** [comment]
I'll take this one
