### ISSUE TITLE
Replace instances of Fragment with <>

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#273]
<> is a shorthand for Fragment and doesn't require an import. See https://reactjs.org/docs/fragments.html#short-syntax. Note that if a fragment is part of an array map, it needs to be explicitly a Fragment so it can get a key prop (https://reactjs.org/docs/fragments.html#keyed-fragments).

**Comment by ChaseC99** [comment]
Example for `NotificationSnackbar.js`
```diff
- <Fragment>
+ <>
    <IconButton
        key="close"
        color="inherit"
        onClick={() => {
            this.props.closeSnackbar(key);
        }}
    >
        <CloseIcon className={classes.icon} />
    </IconButton>
- </Fragment>
+ </>
```

**Comment by RandyHuynh5815** [comment]
I'll take this issue.
