### ISSUE TITLE
Change "Settings" navbar item to "Theme"

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#277]
Currently we have a Settings navbar item. However this is just for the theme to toggle dark mode. 
<img width="611" alt="image" src="https://user-images.githubusercontent.com/29494270/157638548-370ddc40-2350-4f4b-9484-acf105d1989e.png">

- Rename this to "Theme" and change the icon to the Brightness4 icon: `import { Brightness4Icon } from '@material-ui/icons/Brightness4';`
- Remove the `<FormLabel>Theme</FormLabel>` from the popup box

**Comment by AnthonyCusi** [comment]
I'll do this one!
