### ISSUE TITLE
Resolve FormLabel warning

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#284]
When you run `npm start` there is a compiler warning 
```
./src/components/App/SettingsMenu.js
[FRONTEND]   Line 2:49:  'FormLabel' is defined but never used  no-unused-vars
```
<img width="1338" alt="image" src="https://user-images.githubusercontent.com/29494270/158007489-839cca56-0a50-4aab-8cdc-96e383c81f31.png">

Find and fix this warning.

**Comment by wamfoo** [comment]
I'll take this one.
