### ISSUE TITLE
Download Button unresponsive

### ISSUE THREAD

**Issue by ACEslava** [icssc/AntAlmanac#295]
When clicked, download button does not prompt user to save .ics file.

![image](https://user-images.githubusercontent.com/32086325/158261595-c1f5bfe6-2101-41cc-a7e6-278c18440bee.png)

**Comment by ChaseC99** [comment]
Thanks for bringing this to our attention! There's a PR out for this now and we will have it deployed shortly.

**Comment by ChaseC99** [comment]
The fix for this has been deployed 🚢
