### ISSUE TITLE
Improve backend development process

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#297]
In #289, we took the backend out to simplify frontend development. 
To run the backend locally, the frontend requires a code change (see the [README](https://github.com/icssc-projects/antAlmanac/#running-the-backend)).

We should figure out how to run the backend locally without a code change.

**Comment by ChaseC99** [comment]
Idea: 
- Add the `.gitmodules` file back to the project
```
[submodule "antalmanac-backend"]
	path = antalmanac-backend
	url = https://github.com/icssc-projects/antalmanac-backend
```
- Add antalmanac-backend to `.gitignore` so it doesn't get committed
- Add an npm script to install the backend
```
"install-backend": "git submodule update --init --recursive"
```
- Add an npm script to run the frontend and backend at the same time, with the frontend using localhost:8080 as a proxy.
    - Not sure how to update the proxy at runtime with an npm script. Alternatively, we could pass in an env variable to see which endpoint to use in `endpoints.js`
    - We might also need to add the concurrently dev dependency back in to run frontend/backend together

For anyone who wants to work on the backend, they would just need to run the `install-backend` script and an alternative start script.

**Comment by EricPedley** [comment]
I'd say we can call this finished as of #514
