### ISSUE TITLE
Create a "Helpful Tips" box

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#303]
There's a lot of AntAlmanac features that user don't know about
- SMS Notification
- Export to Google Calendar
- Custom Events
- Map routes
- Coming soon: import from Study List

Create a box under the Class Search that rotates through a list of tips, randomly display one per page load

**Comment by ChaseC99** [comment]
Maybe it could even include gifs

**Comment by devsdevsdevs** [comment]
Maybe make use of this empty space for a link/button/callout?
![image](https://user-images.githubusercontent.com/30539874/158499247-ee20cf88-5971-4ad0-80dc-835ad0a6c22b.png)
We can also add something like this: We have this when there's new "News" items 
![image](https://user-images.githubusercontent.com/30539874/158499298-6a578626-06bf-49b3-a77b-9b2bad470250.png)
I myself can't resist not clicking on these 🤣

**Comment by EricPedley** [comment]
We have the helpbox, I think we can close this after doing the thing with news containing old patch notes.

**Comment by MinhxNguyen7** [comment]
Covered by #801
