### ISSUE TITLE
Clicking location pins on the map spawns popup in wrong location

### ISSUE THREAD

**Issue by devsdevsdevs** [icssc/AntAlmanac#304]
Clicking the location pin doesn't accurately place the popup on the pin. This used to work fine, might want to look into changes on map component or its parent components.

![image](https://user-images.githubusercontent.com/30539874/158498137-69da417b-d2a5-466e-ab4c-bd4967a1b73c.png)

**Comment by ChaseC99** [comment]
Hmm I don't even get a popup when I click on it.  
@falsidge can you look into this after finals?
