### ISSUE TITLE
Add a console.log for recruitment

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#305]
A lot of companies will put a console log message on their sites, as a little easter egg for anyone who opens the console. We should do this too and refer people to our github and discord. 

Add something like this to a new script tag in [index.html](https://github.com/icssc-projects/AntAlmanac/blob/main/public/index.html):
```
console.log("Interested in improving AntAlmanac?\n - Checkout the project on GitHub: https://github.com/icssc-project/antalmanac\n - Join our Discord: https://discord.gg/GzF76D7UhY\n - Leave feedback: https://antalmanac.com/feedback")
```

Feel free to get creative with the formatting/content! There's lots of cool examples online of how to do this: https://thenewstack.io/tutorial-getting-creative-with-console-statements/

**Comment by wwesleym** [comment]
i'll take this one!
