### ISSUE TITLE
Improve "different terms" warning trigger

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#319]
We have a warning that shows up when you add classes from different schedules
<img width="484" alt="image" src="https://user-images.githubusercontent.com/29494270/160225425-49cf3c08-074e-4f0c-9fc7-7e3ade9e9c34.png">

This warning erroneously appears if:
- you have a different term on another schedule (e.g. "Schedule 1" is 2022 Spring and "Schedule 2" is 2022 Winter)
- you clear an old schedule (e.g. press the delete button to clear "Schedule 1" which was 2022 Spring and then try to add a 2022 Winter class)
- you import a schedule for one term into another term (#302), it sends multiple warning banners instead of one

**Comment by ecxyzzy** [comment]
> you clear an old schedule (e.g. press the delete button to clear "Schedule 1" which was 2022 Spring and then try to add a 2022 Winter class)

I can't seem to reproduce this behavior with the build deployed to prod—is there a specific case that triggers it?

Also while we're on the note of sending (possibly too many) banners, do we still want to alert the user every time they add a course to a schedule with multiple terms when they've already added a course from one of those terms?

**Comment by ChaseC99** [comment]
> do we still want to alert the user every time they add a course to a schedule with multiple terms when they've already added a course from one of those terms?

Yes, schedules should not have multiple terms.
