### ISSUE TITLE
Handle http connections

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#321]
For some reason, the "Enforce HTTPS" button was unchecked on GitHub pages. I had to manually re-check it.
![image](https://user-images.githubusercontent.com/29494270/160564845-b655e1a6-b921-4f9a-9ad1-764e0c4ac44c.png)
I don't know how this happened but when it does, there's a chance that the user will accidentally go to http://antalmanac.com instead of https://antalmanac.com. The server won't respond to http, so the schedule will fail to load.

I'm not sure how we want to safe guard against this scenario. We could either display a warning banner when the site is http or maybe force a redirect to https on the client side. Open to other suggestions too though.

**Comment by taesungh** [comment]
GitHub pages automatically redirects HTTP requests to HTTPS by serving status 301 with the secure location, so from my understanding, no further action is needed here.

**Comment by ChaseC99** [comment]
Correct, it currently works fine.

However if something goes wrong and http is served instead, our backend will reject any API requests because of our CORS policy. The frontend should handle this edge case more gracefully than the current "Could not find schedule" snackbar error message that makes users think their schedule was deleted.

**Comment by EricPedley** [comment]
IDK how a user would end up on the HTTP site, closing this to clear up the issue queue.
