### ISSUE TITLE
Calendar Color picker closes when clicking inside the Color picker popup

### ISSUE THREAD

**Issue by falsidge** [icssc/AntAlmanac#323]
The calendar color picker popup should stay open when selecting a color and close when clicking anywhere outside the popup.

This is due to changeCourseColor sending a addedCoursesChange action causing a updateCurrentScheduleIndex, which closes all popups in ScheduleCalendar.js. A simple solution is to remove the handleClosePopover, but popups will not close when classes are added or updated. Another is to add a different action for colorChange, which could also fix the color not updating in course panel

**Comment by ecxyzzy** [comment]
Closing since #326 was merged.
