### ISSUE TITLE
Google Calendar Timezone

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#324]
Importing the downloaded ICS file to Google Calendar puts the events 7 hours off because it interprets them as UTC time instead of PST.  To fix this, we need to add a `VTIMEZONE` section to the ICS file, like this:
```
BEGIN:VTIMEZONE
TZID:America/Los_Angeles
X-LIC-LOCATION:America/Los_Angeles
BEGIN:DAYLIGHT
TZOFFSETFROM:-0800
TZOFFSETTO:-0700
TZNAME:PDT
DTSTART:19700308T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=2SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
TZOFFSETTO:-0800
TZNAME:PST
DTSTART:19701101T020000
RRULE:FREQ=YEARLY;BYMONTH=11;BYDAY=1SU
END:STANDARD
END:VTIMEZONE
```
it goes between `X-WR-TIMEZONE` and `BEGIN:VEVENT`

**Comment by EricPedley** [comment]
I'm seeing now that we're using a library to manage the ics file downloads so just adding that section to the ICS file might not be the solution we're looking for.

**Comment by ChaseC99** [comment]
For now, let's add a tooltip reminding user to put their calendar in PST
