### ISSUE TITLE
Migrating away from Flux

### ISSUE THREAD

**Issue by ecxyzzy** [icssc/AntAlmanac#334]
The version of `flux` we currently ship is out of date and depends on a deprecated version of `core-js`. In addition, the `flux` project as a whole is in maintenance mode, so it would likely be better in the long run to migrate to another application architecture.

**Comment by EricPedley** [comment]
While reading [_How to Write Unmaintainable Code_](https://www.mindprod.com/jgloss/unmaindesign.html), I found this passage that reminded me of our flux event system:
![image](https://user-images.githubusercontent.com/48658337/163924390-ed477b01-e0d4-4450-b7f9-9e2803d25a9c.png)
