### ISSUE TITLE
Update recharts

### ISSUE THREAD

**Issue by ecxyzzy** [icssc/AntAlmanac#335]
The version of `recharts` we use depends on a deprecated version of `core-js`. Upgrading probably won't affect existing functionality since the graph modals are currently hidden, but the graph modal rewrite should use the updated version instead.

**Comment by JacE070** [comment]
The Current version is 1.8.5, the Wanted version is 1.8.6, and the Latest version is 2.3.2. Should we just update it from 1.8.5 to 1.8.6?

**Comment by MinhxNguyen7** [comment]
Isn't this completed per #469? The installed version is 2.4.3
