### ISSUE TITLE
Google Analytics 4 Migration Part 1

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#337]
We need to migrate to GA 4 by July 1, 2023.

Let's setup a new GA account under the ICSSC email. Other projects will also be using this account.

**Comment by ChaseC99** [comment]
@EricPedley I've shared the old AntAlmanac Google Analytics account and the new ICSSC one with your uci email.

**Comment by EricPedley** [comment]
Changed title because I'm splitting this up into two PRs since theres a bunch of changes.
