### ISSUE TITLE
Grades Modal

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#340]
- Create a drop down grades graph. This can be a simple bar graph. 
- Rename the button from "Zotistics" to "Past Grades"
- At the bottom of the bar graph, show a button that says "View on Zotistics" that links to more info.

Here is an example of what ZotCourse does: 
<img width="383" alt="image" src="https://user-images.githubusercontent.com/29494270/163047515-70c06450-376b-4824-a92f-7ed7824fdcf0.png">

It's up to you how much you want to implement inside the bar graph. I'd say start with just the average from the course and then later we can add more specific bars like Instructor and last offering.

**Comment by kartik-bhagatwala** [comment]
Just wanted to give a progress update of what I have so far with commit [08a7547](https://github.com/icssc/AntAlmanac/commit/08a75470a467f4c6ed90414ff4ea8eb364309b6d). I want to test more, including mobile usability before submitting a PR. I think the instructor grades comparison shouldn't be too hard to implement as well.

![image](https://user-images.githubusercontent.com/30458137/167790955-bf6bf1f6-a84a-4c9c-b2e6-0442a49e9b72.png)

**Comment by ChaseC99** [comment]
Looking great! 
One design note: the "Grades" button can replace "Zotistics". We can hide the external link to Zotistics inside of the modal.
