### ISSUE TITLE
Past Enrollment Modal

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#341]
- Create a drop down enrollment graph. This can be a simple line graph.
- At the bottom of the bar graph, show a button that says "View on ZotTracker" that links to more info.

Here's a suggested design from Design at UCI. No need to follow it exactly but feel free to use it for inspiration. 
![image](https://user-images.githubusercontent.com/29494270/163047397-16fe8d77-0e22-410e-a445-232eaf076a8c.png)

**Comment by Douglas-Hong** [comment]
The enrollment history endpoint was just added to PeterPortal API, so we can proceed with bringing back this graph.

On ZotTracker, I will also start using the API instead of my custom scraper and MongoDB cluster.
