### ISSUE TITLE
Fuzzy Search: Use web workers to execute fuzzy search code

### ISSUE THREAD

**Issue by ecxyzzy** [icssc/AntAlmanac#345]
Certain larger queries cause a visible delay between input completion and the component re-rendering to reflect the input text and the recommendations. For instance, the query `ics` causes my browser (Firefox 99.0.1) on my laptop to become unresponsive for ~200ms. This is mitigated to an extent by caching, so subsequent queries don't incur the same performance cost, but this will always happen to the initial query.

A solution would be to use web workers to run `search()`, so the main thread isn't blocked and the app doesn't freeze completely for the user. However, this is not feasible with the current version of webpack we ship, and so will have to wait for #279.

**Comment by MinhxNguyen7** [comment]
Can't reproduce. It's as fast I can perceive when I tried it on my Chrome and Firefox installations.
