### ISSUE TITLE
Course Code :onhover looks bad in dark mode

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#354]
When hovering over a course code, the color turns purple. This looks fine in light mode but is hard to see in dark mode.
![image](https://user-images.githubusercontent.com/29494270/164183019-d1db92e6-f7fb-45a9-81c4-919976fa0f7e.png)

**Comment by SenghoungLim** [comment]
Claimed. I planned to change blue violent to gold color in dark mode. Or is there a particular color palette I have to follow?
