### ISSUE TITLE
Improve course number analytics

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#378]
Right now, the analytics event for course codes only captures the whole number part of the course number, so classes like writing 39 a,b,c and cs 122a,b,c,d will all just appear as "writing 39" or "cs 122" on the analytics page. Since GA can track decimals in the values, it would be nice to represent the alphanumeric course codes as decimals, like 39a -> 39.1, 122c -> 122.3
The part you would need to change to do this is in `AppStoreActions.js`
![image](https://user-images.githubusercontent.com/48658337/168448355-7618eb5e-e6a8-4f41-9d4e-3f9c122346e8.png)
`courseDetails.courseNumber` is a string such as `'39a'`, `'122d'`, or `'121'`

**Comment by rlmech** [comment]
Going to try this one

**Comment by EricPedley** [comment]
> Going to try this one

GL. This one is kinda tough because there are a lot of edge cases. The committe discussed this on Discord around a month ago:
![discord thread screenshot 1](https://user-images.githubusercontent.com/48658337/172270108-f03d4a85-8737-49ce-8904-0952f3d51b38.png)
![discord thread screenshot 2](https://user-images.githubusercontent.com/48658337/172270119-365b8d49-de0d-434c-9855-80d829e2ea3d.png)
And we didn't really reach any conclusions about the best way to do it. The TLDR of that discussion was that there are courses with letter prefixes, as well as multiple letters, prefixes AND suffixes, or letters higher than J (the 10th letter), so simple decimal encoding won't work. If you really want to work on this still, just pretend that courses only have a 1-letter suffix less than J, and if that isn't the case, just drop all the letters. Let me know if you need more clarification.

**Comment by rlmech** [comment]
Hello @EricPedley,
I chose the problem a few days ago because I thought it was interesting and would be a slight challenge, but ended up busy because of finals. I'm now finished with finals and tried attempting the problem; however, I frankly do not understand what I am supposed to be doing. Is it possible to discuss over Discord on Friday or Saturday?

**Comment by EricPedley** [comment]
The goal is basically to convert the course code strings into numbers. Some course codes have letters in them, and the goal is to parse the numbers in a way that makes sense. For now, just ignore all leading letters and only convert the first 10 letters of the alphabet to numeric digits.
Some test cases for you:
`ABC123` -> `123`
`122A` -> `122.1`
`45c` -> `45.3`
`112lr` -> `112` because both letters are >9 when converted
`m124b` -> `124.2`
I prefer to keep communication on this GitHub thread but you can contact me on Discord if you want. I'm `@Eric` on the ICSSC Projects server.
