### ISSUE TITLE
Create a `getDefaultTerm()` function for `termData`

### ISSUE THREAD

**Issue by ecxyzzy** [icssc/AntAlmanac#382]
Currently, the expression `termData[defaultTerm]` is used to access the default term, which is not the most concise.

Create a function `getDefaultTerm()` in [`termData`](https://github.com/icssc/AntAlmanac/blob/main/src/termData.js) which returns that expression, and make sure all usages of the expression are replaced with this function call. Optionally, also make sure `defaultTerm` is no longer accessible from outside of `termData`.

**Comment by serisummer** [comment]
I'll claim this one.
