### ISSUE TITLE
Add link to Course Reviews on PeterPortal

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#387]
In SectionTable.js, add a new `CourseInfoButton`

This button should go after the Prereqs button and before Zotistics. 

Use the following for the Button's props:
- `analyticsCategory` should `analyticsCategory`
- `analyticsAction` should be `analyticsEnum.classSearch.actions.CLICK_REVIEWS`
- `text` should be `"Reviews"`
- `icon` should be the RateReview icon
- `redirectLink` should be `'https://peterportal.org/course/` with the `encodedDept` and `courseDetails.courseNumber` added onto the end

Ideally, it looks something like this 
<img width="712" alt="image" src="https://user-images.githubusercontent.com/29494270/170122459-23b113e8-09e2-485b-8c71-78fa012b4000.png">

**Comment by sirAvent** [comment]
Claim!
