### ISSUE TITLE
Fix typo 'anlyticsAction'

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#388]
https://github.com/icssc/AntAlmanac/blob/a720bd636af9da1ada95235c86af2e3f8832cdde/src/components/SectionTable/CourseInfoButton.js#L15

In CourseInfoButton, there was a typo. `'anlyticsAction'` is missing an 'a'.

```diff
- anlyticsAction
+ analyticsAction
```

### TODO:
- Fix the typo in CourseInfoButton.js 
- Fix the typo everywhere that CourseInfoButton was used
- Add `analyticsAction` and `analyticsCategory` to `CourseInfoButton.propTypes` (at the bottom of CourseInfoButton)

**Comment by andrewsantoyo** [comment]
I'll take this one!

**Comment by ChrisTrannn** [comment]
I'll take this!
