### ISSUE TITLE
Missing waypoints for course section with fake locations

### ISSUE THREAD

**Issue by ecxyzzy** [icssc/AntAlmanac#390]
If a section with a "fake" location (e.g. `TBA`, `VRTL REMOTE`, `ON LINE`) is present in a schedule, waypoints do not render properly on the map. The "all" view shows no waypoints or paths at all, and views for individual days show waypoints only if all sections with meetings that day have a real location. Any paths between sections with real locations are still rendered, though without waypoints.

**Comment by EricPedley** [comment]
Still broken on schedule `maptbabug`
