### ISSUE TITLE
Fuzzy Search: Cache persistence

### ISSUE THREAD

**Issue by ecxyzzy** [icssc/AntAlmanac#391]
The current implementation of caching in the `FuzzySearch` component works in theory, if not for the fact that the component is unmounted every time a search is conducted, so the cache isn't actually persistent.

Considering moving the cache to `RightPaneStore`, or waiting on #334 since that will shake things up. Alternatively, if #345 actually gets off the ground and has significant performance benefits, we might not even need a cache.

**Comment by EricPedley** [comment]
@ecxyzzy is this ever gonna happen? We're going through old issues rn.

**Comment by ecxyzzy** [comment]
I think this was one of my ideas way back when to improve performance, but Minh mentioned in #345 that performance doesn't seem to be an issue. Feel free to close if so.
