### ISSUE TITLE
Move Prerequisites Link

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#393]
The Prerequisites button is redundant since we also display the prereqs inside of the course info.

- [ ] Remove the Prerequisites button
- [ ] Make the "Prerequisites" text (highlighted in the image below), link to the prereqs page like the button does.

![image](https://user-images.githubusercontent.com/29494270/171331260-99862f7f-6dce-4bf8-8958-bff4ac63c74f.png)

**Comment by danielianreyes** [comment]
Claim! :)

**Comment by EricPedley** [comment]
It would also be cool if we could display the PeterPortal prerequisite tree as a modal somehow on our site. Probably outside the scope of a fellowship task and might require some coordination with the PeterPortal team, so I'll create an issue for that part once this issue gets resolved. If you think you can tackle this right now though, go ahead.
![image](https://user-images.githubusercontent.com/48658337/173262526-e7cdc6cc-807c-491e-a2be-9bc95ea892cf.png)

**Comment by ChaseC99** [comment]
Oh yeah that is a good idea! Let's create a separate issue for it.
