### ISSUE TITLE
Class location links should open maps tab

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#394]
Right now, when you click a class link in the calendar or section table, it opens up https://map.uci.edu/.

Instead, we should show some love to the Maps tab. It would be cool if clicking it opened the maps tab and selected that building.
![image](https://user-images.githubusercontent.com/29494270/171332111-ec26cfe7-3cff-43bb-b8e8-ed028dcd67bc.png)

**Comment by MinhxNguyen7** [comment]
I can do this, if you don't mind someone outside the team doing it. I'm already halfway done with it.
