### ISSUE TITLE
Update and refactor Snackbar

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#401]
## The task
Update our `notistack` version to 2 and use the enqueueSnackbar hook directly in every component that needs to open a snackbar. This should work for all components, but there are some calls from `helper.js` that might not work because it isn't a component so can't use a hook. It's up to whoever tackles this to research how to fix that.
## The motivation
While reading through the code to figure out areas we can refactor to make onboarding easier, I found the SnackBar is an egregious example of overcomplication. Whenever our components want to open a Snackbar, tracing what actually happens follows this path:
- any component calls the `openSnackbar` funciton in `AppStoreActions`
- dispatcher dispatches `OPEN_SNACKBAR` event
- AppStore receives `OPEN_SNACKBAR` event. Note that you can only figure this out by searching the entire project for the string `OPEN_SNACKBAR`, as there's no direct way to follow where the dispatched event goes
- AppStore emits a `openSnackbar` event using its EventEmitter superclass
- NotificationSnackbar, having already registered a handler with AppStore's EventEmitter upon its creation, gets its `openSnackbar` method called. Again, no way to figure this out without searching for the `openSnackbar` string because it isn't clear what components add listeners to AppStore
- NotifiactionSnackbar's `openSnackbar` method actually calls the library's function to show the snackbar

I feel like the whole event emitter system makes it really hard to figure out what is actually happening for certain events as a new developer because the code that actually does the action is hidden behind multiple layers of code that is hard to trace. Untangling the snackbar from this system will help us get rid of it eventually and make it easier for new developers to understand. Related: #334

Also, the library for the snackbar, `notistack`, doesn't even have docs for our version anymore. The latest stable version is `2.0.5` and we're on version 1 still, which doesn't even have live docs on their website.

**Comment by ap0nia** [comment]
Will be done? Has been done? #503 contains a version of the app that relies on the `useSnackbar` hook in an React-idiomatic way

@EricPedley maybe close?

**Comment by EricPedley** [comment]
We're on notistack 2. Closing.
