### ISSUE TITLE
Add tooltip to "Import" button

### ISSUE THREAD

**Issue by ChaseC99** [icssc/AntAlmanac#414]
In the app bar, some of the items have tooltips explaining what the button does. For example, "Feedback" says "Give Us Feedback!"

<img width="158" alt="image" src="https://user-images.githubusercontent.com/29494270/180158275-4ff04846-b076-407b-8ace-28cf3594e504.png">

"Import" is missing one though! 
Add a tooltip to the "Import" button that says "Import a schedule from your Study List" 

Hint: wrap `<ImportStudyList />` in a [`<Tooltip>`](https://mui.com/material-ui/react-tooltip/)

**Comment by KevinWu098** [comment]
I got this one :)
