### ISSUE TITLE
Remove Google Analytics v3

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#416]
We've switched to version 4 and it's been running successfully for 3 months so it's safe to get rid of the legacy version.

- [ ] Remove all ReactGA imports and function calls. The Search function in VSCode is your friend here (`ctrl+shift+f`)
- [ ] Remove `react-ga` from `package.json` dependency list
  - [ ] Make sure to run `npm i` and commit the resulting `package-lock.json` update

**Comment by JacE070** [comment]
> Remove react-ga from package.json dependency list
By the package.json do you mean package-lock.json? I only found this file.

**Comment by JacE070** [comment]
I've already submitted a PR for this!
