### ISSUE TITLE
Resizable Menus

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#431]
Make the calendar and right panes resizable like ZotCourse does: https://zotcourse.appspot.com/
This is the code block that does it:
https://github.com/jogplus/zotcourse/blob/master/zotcourse/static/js/zotcourse.js#L604
I'm labeling this as `good first task` since it seems like all we need to do is add a library plus a few lines.

**Comment by ap0nia** [comment]
Done! #507
