### ISSUE TITLE
Ampersand does not escape properly in department name

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#464]
See image.

![image](https://user-images.githubusercontent.com/64875104/215557313-2e2a79db-ac83-4a2e-b884-5d8c7224fb7e.png)

To reproduce:
Search for department with ampersand (I only know of EECS)

**Comment by MinhxNguyen7** [comment]
The response from PeterPortal has the escaped ampersand in the department name. I can clean it up, but I'm not sure if that's idiomatic. @ecxyzzy is that expected behavior?

**Comment by ecxyzzy** [comment]
Resolved in icssc/peterportal-api-next@7d9ab02.
![image](https://github.com/icssc/AntAlmanac/assets/89349085/074b1efa-59e5-4efe-b339-a67848518a08)
