### ISSUE TITLE
Refactor withStyles for better IDE searching

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#466]
Using `default export withStyles(styles)(Component)` makes it much more cumbersome to find references with an editor. IMO, it should be `const Component = withStyles(styles)((props) => { /*body*/}); export default Component`. This _should_ be simple with some scripting.

**Comment by EricPedley** [comment]
Closing because this will be handled by #279 since muiv5 has no withStyles
