### ISSUE TITLE
Make every class search parameter sharable

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#558]
Whenever you search, it should update the URL with query params for all the options in your search query and you should be able to copy/paste it and load the search again, just from the URL. Also, when you load the URL it should fire the search query upon load instead of waiting for the user to press enter or search.

**Comment by calejvaldez** [comment]
Hi. I'm trying to work on this, but I'm trying to figure out what part of the code "triggers" the search to begin. I have the parameters on the search bar already, now I'm just trying to trigger a search with the parameters.

These are the changes I've made so far: https://github.com/calejvaldez/AntAlmanac/commit/e172c1d3baa4d5c76b31fc0525ac7b03a80d2b1f

**Comment by EricPedley** [comment]
It's a bit complicated: one of either `FuzzySearch` or `LegacySearch` updates the form values in the `RightPaneStore`, then toggles the view in `CoursePaneRoot` from `SearchForm` to `CourseRenderPane`. `CourseRenderPane` then gets the form values from `RightPaneStore` when it is mounted, queries PeterPortal API's websoc endpoint to do the search, then writes the query results to its internal state, and uses that to render the results.

To answer precisely, the `SearchForm` component gets passed a function as a prop, `toggleSearch`, that it runs as a callback when the user submits the form. Before that function is called, all the form values need to be set in the `RightPaneStore`

Lmk if you have more questions, I'm glad someone is tackling this feature.

**Comment by MinhxNguyen7** [comment]
@ap0nia might want to comment on this since he implemented the router. Otherwise, I can take a look and suggest how you can do this.

**Comment by calejvaldez** [comment]
Hi all. I think I've gotten a bit too busy, and I don't see myself finishing this anytime soon. I'm going to unassign myself for now.
