### ISSUE TITLE
Allow pinch-zoom for mobile

### ISSUE THREAD

**Issue by Douglas-Hong** [icssc/AntAlmanac#565]
If we look at the calendar on mobile, some of the information for a course is cut off (particularly the location). We should add some way to pinch-zoom and allow the user to see more information.

Example:
<img width="208" alt="image" src="https://user-images.githubusercontent.com/78244965/236927881-909e5b02-0bca-4ff6-89b0-39c1a9d60a2d.png">

**Comment by EricPedley** [comment]
Too tough since we have no control over the calendar. We would need to change our calendar library to something that supports this.
