### ISSUE TITLE
Deal with multiple buildings

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#592]
Right now we only display the first one.
(snippet from `apps/antalmanac/src/stores/calenderizeHelpers.ts`):
![image](https://github.com/icssc/AntAlmanac/assets/48658337/25557948-aa51-4980-96f4-b81b15471a4a)

**Comment by alanchangxyz** [comment]
my js is rusty after being off of an IDE for weeks so this is going to be my annual 1x icssc open source contrib 😅

**Comment by EricPedley** [comment]
For testing purposes, using ENGRMAE 295 Fall 2023 (section code 19177) as it's the first course I found that has two locations. Leaving this comment here so nobody needs to dig up an example on their own.

**Comment by KevinWu098** [comment]
Closed by #696
