### ISSUE TITLE
swap the positions of the prerequisites and dependencies in the prerequisite tree modal

### ISSUE THREAD

**Issue by teresa-liang** [icssc/AntAlmanac#613]
Currently, the prerequisite tree is structured so that it shows the dependencies then the 
actual course and then the prerequisites. 

![Image](https://github.com/icssc/AntAlmanac/assets/83627792/e4964d48-f6e8-4ab9-846c-b75311443718)

However, it would be better for the prerequisites to be on the left side to conform to left-to-right reading conventions.

**Comment by teresa-liang** [comment]
Goal: figure out a solution in 2 weeks (10/19)

**Comment by KevinWu098** [comment]
Going to close this PR, as iirc we decided that reversing the tree would create more issues with naming; also, it would affect consistency with Peterportal-Client's prereq tree

Feel free to reopen if I'm wrong above -- it's been a while, so I wouldn't be surprised if I'm misinformed
