### ISSUE TITLE
Remove add to specific schedule dropdown

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#616]
110 people used it (out of 12000+).

**Comment by EricPedley** [comment]
![image](https://github.com/icssc/AntAlmanac/assets/48658337/d50fc1c3-03af-4ea2-b5f3-6f9b1d65abba)
Also 0 revenue generated 😢

**Comment by KevinWu098** [comment]
My favorite feature!

![emoji-disintergrating](https://github.com/icssc/AntAlmanac/assets/100006999/30adfa8c-c0e2-401b-8f61-c72d81208e51)

**Comment by MinhxNguyen7** [comment]
The point of removing the dropdown is to have more space for other things in a row, but the delete and change color buttons always have to be there, so there's not really a point.
