### ISSUE TITLE
RFC: UI/UX Changes Brainstorming

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#617]
- Limit schedules to only have one term, and group schedules by term in the selector, and make the term selector only available in the create or edit schedules menu, lock add to schedules dropdown to only schedules with the same term, or any schedule for custom events.
- Possibly move custom events button to right pane?
- Ribbon with all buttons?
- Move screenshot button since it's rarely used?

![image](https://github.com/icssc/AntAlmanac/assets/48658337/b1841e02-d995-4026-9e61-20d6ad7dafc4)

**Comment by KevinWu098** [comment]
I'm a fan of how ZC has their sectionTable overflow on the page and be scrollable (both mobile and desktop iirc).

Thoughts on implementing this? Especially for mobile, this would make the UI less cramped!

<sub> Am on mobile currently so enjoy some vertical screenshots 😋 <sub>

![Zotcourse](https://github.com/icssc/AntAlmanac/assets/100006999/b9ccd70c-51d3-466a-8e4c-bd481e3e5a06)

![AA 🐜](https://github.com/icssc/AntAlmanac/assets/100006999/fe7ee7d9-ba0b-49fc-a646-a2effd5d1de6)

**Comment by MinhxNguyen7** [comment]
> I'm a fan of how ZC has their sectionTable overflow on the page and be scrollable (both mobile and desktop iirc).
> 
> Thoughts on implementing this? Especially for mobile, this would make the UI less cramped!

Yeah that's actually exactly what we decided on for #600

**Comment by KevinWu098** [comment]
> > I'm a fan of how ZC has their sectionTable overflow on the page and be scrollable (both mobile and desktop iirc).
> > Thoughts on implementing this? Especially for mobile, this would make the UI less cramped!
> 
> Yeah that's actually exactly what we decided on for #600

Banger, great minds think alike 😋

**Comment by KevinWu098** [comment]
@EricPedley 

I think we can close this issue:
1. Will be implemented by Google Auth PR
2. Not a pressing concern as we redid the calendar toolbar, so custom events button (and the toolbar as a whole) has more than enough space
3. Not sure if necessary -- also we're doing a lot of cleanup around AppBar w/ the SettingsMenu, removing News, etc, so it might be better to circle back to this later
4. Done
