### ISSUE TITLE
#574 was reverted

### ISSUE THREAD

**Issue by KevinWu098** [icssc/AntAlmanac#622]
The changes from #574 were reverted, the colors are no longer pretty :(

<img width="1728" alt="Screenshot 2023-06-11 at 7 35 13 PM" src="https://github.com/icssc/AntAlmanac/assets/100006999/2cc0628d-e681-4594-bd36-2e5b900ef06d">

**Comment by Voark** [comment]
That's definitely on me I did some merge conflicts too fast and undid your changes oops. Maybe make the pr again?

**Comment by KevinWu098** [comment]
Yup I'll hop to in the morning :).
