### ISSUE TITLE
Add 24-hour time format

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#637]
Add an option for users to switch the displayed time from 12 hour am/pm to 24-hour format. This issue includes figuring out where we should put the toggle option on the UI.

This was a feature request from the feedback form.

**Comment by suzachary** [comment]
Requesting to work on this issue

**Comment by MinhxNguyen7** [comment]
@suzachary are you still working on this? If you are working on it, do make a draft pull request so we can see if you're headed in the right direction. Thanks!

**Comment by suzachary** [comment]
@MinhxNguyen7 Apologies, I have not been working actively on this for a while. If you're asking because this issue is time sensitive, I would be more then glad to drop it and assign it to someone else. Otherwise, I can start working on it again later this week.

**Comment by MinhxNguyen7** [comment]
No problem. I was just asking to see if we'd change the assignment

**Comment by KevinWu098** [comment]
Writing it here so I don't forget, but this would best be accomplished with a Zustand store and some nifty subscriptions; Take a glance at Tab Store for code!
