### ISSUE TITLE
Dependency and Script from #620 removed by #563

### ISSUE THREAD

**Issue by KevinWu098** [icssc/AntAlmanac#648]
Merging #563 removed the following which were added as part of #620:

1. `"@packages/antalmanac-types": "*"`
2. `"start:local": "VITE_LOCAL_SERVER=true vite"`

Regarding # 1, the removal of this package resulted in DX problems during development, but didn't actually break any builds or prevent work from being done. 

![image](https://github.com/icssc/AntAlmanac/assets/100006999/0ff712d8-8c6f-40e3-a1cb-e33b0aab1f49)

Regarding # 2:

>VITE_LOCAL_SERVER env variable gets set so when developing the frontend uses localhost for the api, otherwise it will just use the dev.api.antalmanac.com endpoint.
-- Fred

The dependency and script were removed due to #563, so closer inspection of packages when submitting a PR would help to resolve/prevent these issues from reoccuring!

**Comment by EricPedley** [comment]
ok, super-duper-nit on this issue itself, but when I was reading it again to get context for #649 it wasn't immediately clear exactly why we needed those two things to be added back, so in the future it would help to also write down the root cause of the issue. Although this is definitely better than no issue at all and I understand writing a longer issue is also more work, so it's really up to you to decide the tradeoff you want to make for spending your time upfront in exchange for making it easier for other people (or your future self) to understand the context around a problem.

**Comment by KevinWu098** [comment]
> ok, super-duper-nit on this issue itself, but when I was reading it again to get context for #649 it wasn't immediately clear exactly why we needed those two things to be added back, so in the future it would help to also write down the root cause of the issue. Although this is definitely better than no issue at all and I understand writing a longer issue is also more work, so it's really up to you to decide the tradeoff you want to make for spending your time upfront in exchange for making it easier for other people (or your future self) to understand the context around a problem.

I understand what you mean, and I'll make a point going forward to put some more time in to make issues and context more readily apparent! I'll update this issue one I get a chance :). Thanks for the feedback!

***I will note that I don't really know what Vite is doing though 😅

**Comment by KevinWu098** [comment]
Pinging @Voark here for some insights! 😋

**Comment by Voark** [comment]
> Pinging @Voark here for some insights! 😋

VITE_LOCAL_SERVER env variable gets set so when developing the frontend uses localhost for the api, otherwise it will just use the dev.api.antalmanac.com endpoint. Sorry, didn't get notified for the first ping for some reason.

**Comment by KevinWu098** [comment]
> > Pinging @Voark here for some insights! 😋
> 
> 
> 
> VITE_LOCAL_SERVER env variable gets set so when developing the frontend uses localhost for the api, otherwise it will just use the dev.api.antalmanac.com endpoint. Sorry, didn't get notified for the first ping for some reason.
> 
> 
> 
> 
> 
> 

Thanks! I'll update this issue :)). And no worries, I uh... edited in the ping in the original issue, so you're all good on that front 😅
