### ISSUE TITLE
Courses in "Added Courses" greyed out 

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#660]
Per #636, sections in the class search should be greyed out if it conflicts with a section in the schedule. However, because the section table is also used in the added courses pane, every class that has a "real" time gets greyed out. @KevinWu098 I assume you'd know how to fix this, so I'm tagging you.

**Comment by KevinWu098** [comment]
💀 can't believe I didn't catch this while testing, I'll have a fix out ASAP

**Comment by KevinWu098** [comment]
Thanks for finding out and letting me know 💖
