### ISSUE TITLE
Course code Button in calendar should be a Chip

### ISSUE THREAD

**Issue by KevinWu098** [icssc/AntAlmanac#667]
The changes in #626 changed the Button component in the Course Render Pane to a Chip component in order to clean up messy styling. It overlooked the identical component also present in the Calendar Course Event popover. This should be fixed for visual consistency.

<img width="522" alt="Screenshot 2023-08-22 at 3 01 16 AM" src="https://github.com/icssc/AntAlmanac/assets/100006999/0467b1d1-a137-446e-acae-a658f6119c87">

**Comment by MinhxNguyen7** [comment]
+1

**Comment by MinhxNguyen7** [comment]
I'll also add that you should take the `clickToCopy()` function from `helpers.ts` and put it in there because it's made specifically for the section code yet is named and placed as if it has a general purpose.
