### ISSUE TITLE
Buttons in Added Pane behave differently than in Course Pane

### ISSUE THREAD

**Issue by KevinWu098** [icssc/AntAlmanac#693]
The buttons in the Course pane are absolutely positioned, meaning that they will remain in the same place (on the screen) even when scrolled down. This is not the same in Added pane.

The behavior should be the same to maintain consistency; Best thing to do is to probably absolutely position the Added pane buttons as well.

**Comment by srukelman** [comment]
requesting to work on this issue

**Comment by KevinWu098** [comment]
> requesting to work on this issue

Have at it! :D

**Comment by srukelman** [comment]
Created PR (https://github.com/icssc/AntAlmanac/pull/703)
