### ISSUE TITLE
Swapping Themes take very Long

### ISSUE THREAD

**Issue by KevinWu098** [icssc/AntAlmanac#694]
When you have a lot of stuff loaded in on the page, changing the theme takes very very long. I'm not sure if that's something that we can fix, but what I do think can be done is some sort of loading indicator while the theme is preparing to swap over.

![chrome-capture-2023-8-11](https://github.com/icssc/AntAlmanac/assets/100006999/df5b9a4a-aa05-4b04-a83a-668dc005fb3d)

With all of ICS loaded, it took ~7 seconds to change themes.

**Comment by EricPedley** [comment]
Probably something with how we lazy-load the search results but don't unmount the ones you scroll past. IDK if going through the trouble to unmount the results that scroll out of view would make scrolling back up noticably slow though. Might be worth a try if anyone's got the energy to test it out. Agreed that loading spinner might be a good band-aid fix here.

**Comment by KevinWu098** [comment]
The settings menu looks quite a bit different now, and with the ripple effect of the button acting as a pseudo input indicator, a loading spinner is probably not as necessary anymore

Still, investigating unmounting could be useful!

**Comment by KevinWu098** [comment]
Top-tier suggestion from @js0mmer

The cost of rerendering so many components is just too great, so we can either force a full-page reload or navigate the user off of the search results, if they're rendered (my preference is the latter).

Admittedly, this could be jarring, but it's better than blowing up the entire web page.

**Comment by js0mmer** [comment]
An alternative for navigating off search results would be refreshing them so the search is still kept, the user is just sent to the top of the results.

**Comment by KevinWu098** [comment]
> An alternative for navigating off search results would be refreshing them so the search is still kept, the user is just sent to the top of the results.

Brilliant. A generational prodigy. An unparalleled mind.
