### ISSUE TITLE
Skeleton Mode doesn't trigger when no courses are added

### ISSUE THREAD

**Issue by KevinWu098** [icssc/AntAlmanac#704]
In testing #702, I discovered that skeleton mode won't trigger if there are no courses, allowing custom events and notes (which will become available in #702) to be edited.

This issue is caused because the trigger for Skeleton Mode is the failure of `queryWebsoc` found in `Schedules.ts`. However, when there are no courses, queryWebsoc won't be called and won't fail.

**Comment by MinhxNguyen7** [comment]
That's fine though, right? You can't add any courses, and if you add any custom events or schedule notes, that would work just fine.

**Comment by KevinWu098** [comment]
> That's fine though, right? You can't add any courses, and if you add any custom events or schedule notes, that would work just fine.

Yeah, I think we came to the conclusion a few weeks ago that this behavior is fine, since there wouldn't be any immediate problems. I'll close this PR :)
