### ISSUE TITLE
Reverse direction of prerequisite tree

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#721]
Also,
- Coordinate with PeterPortal to maintain consistency
- Change the phrasing of the words on the graph edges to make sure they still make sense

and/or, add arrows to the graph edges to make it clear

This was requested on the feedback form

**Comment by ecxyzzy** [comment]
> Coordinate with PeterPortal to maintain consistency

Projects component library????? :eyes: :eyes: :eyes:

**Comment by EricPedley** [comment]
Closing as duplicate of #613 🤦‍♂️

**Comment by KevinWu098** [comment]
Duplicate ^^
