### ISSUE TITLE
Grade aggregation endpoint change

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#722]
Zotistics graph is broken because peterportal-api-next/88.

I've changed the endpoint over to the new name, `aggregateByOffering`, but the query from before doesn't work.

Example:
```graphql
query Query {
  aggregateByOffering(department: "I&C SCI" ) {
      department
      courseNumber
      instructor
      averageGPA
      gradeACount
      gradeBCount
      gradeCCount
      gradeDCount
      gradeFCount
      gradeNPCount
      gradePCount
  }
}
```
[sandbox link](https://docs.api-next.peterportal.org/sandbox?explorerURLState=N4IgJg9gxgrgtgUwHYBcQC4QEcYIE4CeABAIq6FHAA6SRRAhgOaN4KP0oIBCBA8gGb98ASySMAFGAQAHenhSJU6IlRABJAGQBhIgGUta1UQCUlGnQtEps%2BYpTnLRKBBh4AzggBy8AEb4HlqJuKHgwUCgQeAEW9ABu%2BEwIAOIACgCC0XQs9FJpWi6omUTZUlz5MIW0jiUIWuWVjsV4OQgAIvX2VZY1AGIdRTWeKf1dFjXDBZ10AL40s0gg00A)

@ecxyzzy Can you take a look? Thanks

**Comment by ecxyzzy** [comment]
Should be fixed now (confirmed through query and by testing the graph in prod). Feel free to close if it is indeed working, or just nudge me again if things are still broken.
