### ISSUE TITLE
Zotistics graph has labels on the x axis.

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#728]
Here's what it looks like rn:
![image](https://github.com/icssc/AntAlmanac/assets/48658337/05c1a35c-f9ce-497d-9820-fe4798df6428)

And here's what I'm imagining it should look like:
![image](https://github.com/icssc/AntAlmanac/assets/48658337/8c38fd71-fc43-4d22-95e3-cb13c7895490)
There's questions marks on the last two because I don't even know what they are. My guess is pass and no pass but idk for sure.

**Comment by Douglas-Hong** [comment]
Yeah the last two bars should be for Pass and No Pass. When we query for grades, we use this as the query string, which includes P and NP count at the end:

```javascript
const queryString = `
    { aggregateGrades(department: "${deptCode}", courseNumber: "${courseNumber}", ) {
    gradeDistribution {
    gradeACount
    gradeBCount
    gradeCCount
    gradeDCount
    gradeFCount
    gradePCount
    gradeNPCount
    averageGPA
    }
    },
}`;
```

**Comment by JackyZzZz** [comment]
working on this
