### ISSUE TITLE
Prevent Text-Wrap in SectionTableBody and the Department Card Component

### ISSUE THREAD

**Issue by KevinWu098** [icssc/AntAlmanac#729]
<img width="499" alt="Screenshot 2023-10-12 at 11 09 23 AM" src="https://github.com/icssc/AntAlmanac/assets/100006999/e1cc2b57-289b-416e-97ee-2dcc0574da0c">

):< Long course names make the buttons resize and shifts the UI

The fix should truncate the course names whenever they overflow some predefined min-length of the course info button. This also happens to the School/Dept card.

**Comment by MinhxNguyen7** [comment]
It's probably be easier and more responsive to just make it not wrap and hide the overflow.
