### ISSUE TITLE
Strange behavior for show/hide columns dropdown

### ISSUE THREAD

**Issue by js0mmer** [icssc/AntAlmanac#737]
https://github.com/icssc/AntAlmanac/assets/8922227/85a4e707-2a5c-4aea-bb92-92aafa0d944a

**Comment by KevinWu098** [comment]
Likely has to do with #671 and the changes to Columns; Will investigate following Gassko 6B midterms 😭

**Comment by MinhxNguyen7** [comment]
I'll take it over considering I wrote that code and you've got like 10 issues assigned.
