### ISSUE TITLE
Cache Mapbox Tiles

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#739]
During peak usage we go over the mapbox free tier for the tiles API. We could use another tiles provider but I didn't really like how any of them looked (see #730).

To reduce costs, we could cache the tiles we're getting from the API and make our proxy just return results straight from our cache. My current idea is using S3 or something. Important questions to answer while implementing this:

-    How many unique tiles actually are there around the part of the map we want to load?
-    When do we do cache invalidation? (maybe 1 week or something)
-    How much would adding caching slow down the proxy too much for requests that don't get a cache hit?
-    Can we determine which tiles are in cache already and just request straight from S3 instead of going through our Lambda proxy every time?
-    Should we just ditch MapBox's tiles and use a free static tiles provider? I explored this possibility in the past and didn't find any that looked as good, but I'm not gonna discount the possibility that there is some tileset out there that would also work for our purposes. In this case, we only need to proxy the request to the MapBox directions API.

This one is pretty open-ended since there's some interesting system design questions that are unanswered right now.

**Comment by MinhxNguyen7** [comment]
I'll take a look at this. Not sure if I'm going to take it, but I'm writing this so I don't forget.
