### ISSUE TITLE
Export schedule to .ics doesn't include custom events

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#741]
Also, if your schedule consists only of custom events, the download button doesn't do anything. This is consistent with what happens when you have nothing on your schedule, which is probably also not good, as it should make a snackbar popping up saying it failed to download because your schedule is empty.

**Comment by KevinWu098** [comment]
![disintegrate](https://github.com/icssc/AntAlmanac/assets/100006999/141db1b6-f8fd-487d-93ea-72e9acbff8c0)

**Comment by KevinWu098** [comment]
Okay so, this isn't actually a bug I think? It's a feature 🤭

Similar to how copy schedule doesn't actually copy custom events (which is not necessarily intended, but also not not intended), I think this was just how the code was originally written... (also reminds me to add custom events to copy schedule)

Can't hurt to add the feature though; I'm almost tempted to say `good first task`

**Comment by JacE070** [comment]
Bruh I think my change does this. I thought the issue originally includes this part lol https://github.com/icssc/AntAlmanac/pull/742

**Comment by KevinWu098** [comment]
Closed by #742
