### ISSUE TITLE
Map Markers don't Update in Color

### ISSUE THREAD

**Issue by KevinWu098** [icssc/AntAlmanac#747]
<img width="1383" alt="Screenshot 2023-10-19 at 10 16 28 AM" src="https://github.com/icssc/AntAlmanac/assets/100006999/cf4d98c7-30ff-47d0-9cfb-d770fdb4198c">

To be more clear, when course colors are changed, the Map Markers will not update their color accordingly until the next render.

**Comment by MinhxNguyen7** [comment]
This is among the things that a refactored app store should fix using hooks.
