### ISSUE TITLE
RFC: Finals date

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#758]
It would be useful to see finals' dates in the finals tab in the calendar (next to the day), at least in the desktop version. I haven't looked at whether that's part of the API/WebSOC, but I think it should be pretty easy if it is. 

Maybe we can count back from the end dates of the quarters. Note: pay attention to how Summer session works.

Displaying the date and day with React Big Calendar *should* be as simple as passing flags in.

**Comment by EricPedley** [comment]
Sounds good

**Comment by EricPedley** [comment]
![image](https://github.com/icssc/AntAlmanac/assets/48658337/99a071f3-80ad-48be-a84a-aa1405f8273a)

**Comment by KevinWu098** [comment]
~~https://jquense.github.io/react-big-calendar/examples/index.html?path=/docs/props--formats-day-header-format~~
~~Currently trawling through the RBC docs; this seems interesting and could possibly be the way to implement this PR~~

Nope ^, it was really as simple as adding an additional `MM/DD`

**Comment by KevinWu098** [comment]
This is blocked by issue #778, as to display the proper finals dates, we'd need to use the Calendar endpoint appropriately so that we're not hard-coding in dates

**Comment by KevinWu098** [comment]
Passing this onto other AntAlmanac folk 🫡
