### ISSUE TITLE
Use Calendar endpoint instead of hardcoding term dates.

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#778]
There's an endpoint on PP to get term dates, but we're still hardcoding it like monkeys.

https://docs.api-next.peterportal.org/docs/developers-guide/rest-api/reference/calendar

### Related Issues
#758

**Comment by KevinWu098** [comment]
Terms endpoint is kinda dope >:), but it's not documented ;(

**Comment by KevinWu098** [comment]
Passing this onto other AntAlmanac folk 🫡

**Comment by MinhxNguyen7** [comment]
It's too much of a PITA.
