### ISSUE TITLE
Asymmetrical Calendar Split

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#780]
There's no reason why the calendar needs to be 50% of the screen (on desktop). There's a lot more information in the course pane, so it should be bigger. That should allow us to have a larger font size, improving readability and making the app look less dated.

**Comment by KevinWu098** [comment]
`good first task` doers should take a glance at `Home.tsx` for the relevant code! For reference, ZotCourse uses a 45/55 split for their Split-Pane view, but feel free to select another ratio that looks good to you!
