### ISSUE TITLE
Download ICS test failing

### ISSUE THREAD

**Issue by EricPedley** [icssc/AntAlmanac#793]
The event that is getting produced for a fall quarter course has the winter quarter start date for some reason, and this started after we updated the term list to include winter.
![image](https://github.com/icssc/AntAlmanac/assets/48658337/65c74ccf-281d-4d30-a6ad-95f3660fb4f1)

**Comment by KevinWu098** [comment]
My guess is that this test might call getDefaultTerm() and will create a winter quarter event

**Comment by ap0nia** [comment]
This is incorrect. The **custom event** has the wrong start date. Custom events are assigned the current default term, which has changed. The course still has the correct data because its terms are assigned directly in the object.
