### ISSUE TITLE
Restrictions Column Stops Scrolling

### ISSUE THREAD

**Issue by Douglas-Hong** [icssc/AntAlmanac#798]
If you hover over a cell in the restrictions column, it stops the user from scrolling. In order to continue scrolling, the user has to click away from the cell and then scroll. Ideally, the user can continue scrolling without stopping. If the user scrolls away, make sure the popup from the cell in the restrictions column disappears.

**Comment by EricPedley** [comment]
this just got mentioned in the feedback form
