### ISSUE TITLE
Add copy button to schedule dropdown

### ISSUE THREAD

**Issue by KevinWu098** [icssc/AntAlmanac#804]
<img width="244" alt="Screenshot 2023-11-16 at 10 35 52 AM" src="https://github.com/icssc/AntAlmanac/assets/100006999/5fc81fb9-9d74-49d1-a3c9-f5c6ad0f3b0c">

Since this was refactored, adding in another column for copy button should be straightforward.

**Comment by JackyZzZz** [comment]
By the way, do we want to remove the original copy button in the added menu since we have it in the schedule dropdown maybe?

**Comment by KevinWu098** [comment]
> By the way, do we want to remove the original copy button in the added menu since we have it in the schedule dropdown maybe?

For now, I'd recommend keeping it and updating it so that it uses the same dialog that you implemented for the schedule dropdown. The main reason is the visual inconsistency of having 3 buttons on Search, then 2 on Added, which is exacerbated by the fact that the hide columns button would keep shifting positions. (3rd position on Search, then 2nd on Added).

**Comment by JackyZzZz** [comment]
Cool, will do
