### ISSUE TITLE
AutoSave Feature (Overtaken by #891)

### ISSUE THREAD

**Issue by stevenguyukai** [icssc/AntAlmanac#817]
My friends and I have all experienced closing the browser and finding no savings. Especially for freshmen, they may not know they need to save when they first use this tool. So, I think adding an autosave feature will improve usability. 
 
1. The creation or login UserID is displayed if the user does not automatically log in to the previous UserId when adding a course. 
2. Autosave can call every minute, or every time after adding, deleting, or making any changes (but this may give the server a lot of pressure?).

**Comment by stevenguyukai** [comment]
### Autosave when the user closes the website. (could be a setting) 
Pop up a window to let the users choose to save it, or leave the website.
> Problem: For mobile users, the pop-up may not show. Do you have another autosave feature on mobile?

**Comment by stevenguyukai** [comment]
### The First draft is done. Waiting for review #865

**Comment by KevinWu098** [comment]
Completed by #891
