### ISSUE TITLE
GPA Column is Broken for ICS classes

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#860]
@KevinWu098 conjectures that it's an API change that broke it about a month ago.

@ecxyzzy

**Comment by MinhxNguyen7** [comment]
@ecxyzzy It's only ICS classes. Maybe there's something with escaping the ampersand, but GEN&SEX works just fine.

**Comment by JacE070** [comment]
By looking up Peterportal GraphQL API, I found this:
![image](https://github.com/icssc/AntAlmanac/assets/53324036/7fedb5df-bff9-4d3d-b89f-22897cc21300)
There are two values for ICS which point to the same department.

Things go normal if you put "I&CSCI" as department instead of "I&C SCI".

We can just put a patch rn, but only expediently.

Do we have certain reason for having this? @ecxyzzy

**Comment by JacE070** [comment]
> By looking up Peterportal GraphQL API, I found this: ![image](https://private-user-images.githubusercontent.com/53324036/299889966-7fedb5df-bff9-4d3d-b89f-22897cc21300.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYyNDg4NTEsIm5iZiI6MTcwNjI0ODU1MSwicGF0aCI6Ii81MzMyNDAzNi8yOTk4ODk5NjYtN2ZlZGI1ZGYtYmZmOS00ZDNkLWI4OWYtMjI4OTdjYzIxMzAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI2VDA1NTU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1NDc2ODAxMTk0NGM1NDFjMjBiNTQ3N2Y1MGFlZDM3ZDQ4N2M3NWRjNzYzZDE5YTkwYzQyMWFlOWI3MDQ0MjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2gxlbqKhufsjI_v4U1RZMMzYRzfVwUsVoXAzZ2_XYTI) There are two values for ICS which point to the same department.
> 
> We can just put a patch rn, but only expediently.
> 
> Do we have certain reason for having this? @ecxyzzy

You can get this if you pass the query string and POST to `https://api-next.peterportal.org/v1/graphql`
`query {
  depts {
    deptLabel,
    deptValue
  }
}`

Peterportal playground: https://api.peterportal.org/graphql-playground

**Comment by ecxyzzy** [comment]
Should be resolved now, sorry about the delay.

It looks like something trimmed the spaces of all department codes during the migration to PostgreSQL.

**Comment by KevinWu098** [comment]
Banger 🙏
