### ISSUE TITLE
Preview in Zotistics causes the website to crash

### ISSUE THREAD

**Issue by JackyZzZz** [icssc/AntAlmanac#877]
If you search a course, and you want to get a preview of Zotistics by leaving your mouse on top of the Zotistics button, this error message pops up and causes the whole website to crash:
![image](https://github.com/icssc/AntAlmanac/assets/110846941/6a692d9a-3c3f-4bc8-a456-d113374f2b49)

**Comment by JackyZzZz** [comment]
@KevinWu098 @EricPedley I saw that it got merged already but when I visit the site the error is still reproducible. Is there something went wrong maybe?

**Comment by KevinWu098** [comment]
> @KevinWu098 @EricPedley I saw that it got merged already but when I visit the site the error is still reproducible. Is there something went wrong maybe?

💀 I'm trolling I'll investigate

**Comment by KevinWu098** [comment]
Okay this is not a me problem, this is a deployment problem 😋

> @KevinWu098 @EricPedley I saw that it got merged already but when I visit the site the error is still reproducible. Is there something went wrong maybe?
