### ISSUE TITLE
Deployment to Prod isn't happening

### ISSUE THREAD

**Issue by KevinWu098** [icssc/AntAlmanac#884]
As title suggests, new merges are not being pushed to prod. Guessing it might have somethin' to do with #864?

I know for sure #879 and #880 are not live (manually checked).

@EricPedley @ap0nia 

>               @KevinWu098 @EricPedley I saw that it got merged already but when I visit the site the error is still reproducible. Is there something went wrong maybe?

_Originally posted by @JackyZzZz in https://github.com/icssc/AntAlmanac/issues/877#issuecomment-1928757407_

**Comment by ap0nia** [comment]
I think it's fixed 🤓
