### ISSUE TITLE
Hovered course previews remain if you escape out of search results

### ISSUE THREAD

**Issue by js0mmer** [icssc/AntAlmanac#900]
If you hover over a course with hover to preview on and press escape to go back from the current search results, the course preview will remain in the calendar.

https://github.com/icssc/AntAlmanac/assets/8922227/1fc123e8-386d-4ec6-9518-7733c96968de

**Comment by KevinWu098** [comment]
![an-emoji-disintegrating-in-pain](https://github.com/icssc/AntAlmanac/assets/100006999/9e87fa26-5780-4c07-968e-05cd24e7a4ce)
