### ISSUE TITLE
RFC: Show Specific Major restriction and timeline

### ISSUE THREAD

**Issue by stevenguyukai** [icssc/AntAlmanac#934]
## More clear Major restriction Info
For a course like the one below has a specific major restriction:
![Image](https://github.com/icssc/AntAlmanac/assets/47913844/cb1533c1-1aa6-44e1-9851-79e7a4396322)

## Time Line of restriction release
I think it is better to include a TIMELINE of when I can register for this class and also show on the Antalmanac result the current acceptable major or school. 

![Image](https://github.com/icssc/AntAlmanac/assets/47913844/8205349e-b307-4034-acc0-30802c29412a)

## Adding profile setting - Major/School
For every user, they can choose the major and school they are in, and it will help to determine the register time for every class

**Comment by EricPedley** [comment]
Scraping would be hard but I think we could include links to these pages for each school somewhere on our site. But, it's a lot of work to track down the links for every single school. Maybe only implement this for school of ICS classes? I'm gonna look at the statistics for class searches to see if any other departments are really popular.

**Comment by EricPedley** [comment]
![image](https://github.com/icssc/AntAlmanac/assets/48658337/9633e2bb-0f3a-4a71-9f1d-1ada22c9ccff)

**Comment by MinhxNguyen7** [comment]
Most schools will have this information as part of their comment in WebSOC, which we display. I think that searching all the school websites would be an excessive PITA.
