### ISSUE TITLE
Show GPA column on Added Page

### ISSUE THREAD

**Issue by JackyZzZz** [icssc/AntAlmanac#939]
From the feedback form:

> It would be great if GPA was also displayed in the "Added" page

**Comment by MinhxNguyen7** [comment]
This is a feature, not a bug. I explicitly made the column not show up in the added page. 

That being said, I've come to realize it's a bad feature, and you should be able to view GPA on either pages.

**Comment by MinhxNguyen7** [comment]
Sorry @Douglas-Hong. I swiped this from under you. I didn't realize you were working on it until I finished.
