### ISSUE TITLE
Past Enrollment Dates are NaN on Safari

### ISSUE THREAD

**Issue by Douglas-Hong** [icssc/AntAlmanac#947]
In #944, we found that the dates on the x-axis in the past enrollment popup are `NaN/NaN/NaN` in Safari, as seen in the screenshots in https://github.com/icssc/AntAlmanac/pull/944#pullrequestreview-1926077916. The dates are correct on Chrome and Firefox, but Safari has issues.

It might be helpful to see the response we get from PeterPortal in the `queryEnrollmentHistory` function in `enrollmentHistory.ts`. It also might be helpful to look at `parsedEnrollmentHistory` from `queryEnrollmentHistory`.

**Comment by MinhxNguyen7** [comment]
@KevinWu098 Do you know if this is still the case? I don't have an iPhone to check.

**Comment by KevinWu098** [comment]
> @KevinWu098 Do you know if this is still the case? I don't have an iPhone to check.

![image](https://github.com/icssc/AntAlmanac/assets/100006999/bf4f262c-6dea-45d1-ba57-b6bc87039629)

Still happening on my end
