### ISSUE TITLE
Display class info in search panel even if class isn't offered in the current quarter

### ISSUE THREAD

**Issue by ollykel** [icssc/AntAlmanac#953]
Currently, if you search for a class in a certain quarter, you get this error page:
![No-Class-Found](https://github.com/icssc/AntAlmanac/assets/24789977/1e3219b7-4ebd-4370-af03-0e7b9f1b5790)

Even if the class isn't offered in the selected quarter, it would still be useful to see the class info, reviews, zotistics, and especially past enrollment, since past enrollment gives you an idea of when the course will be offered again. I feel like the error page should look more like this, so you still have some information available:
![Proposal-Preview](https://github.com/icssc/AntAlmanac/assets/24789977/4de43300-0036-45c3-9cb7-fd98a99323e7)

Or even just replace the error image with "No matching classes found this quarter. See Past Enrollment to see when the class was last offered."

**Comment by MinhxNguyen7** [comment]
@ap0nia @srukelman What's the idea on implementing/not implementing this? 

I think it's a fine idea, but it could be a little difficult because you might have to change the API.

**Comment by MinhxNguyen7** [comment]
Thanks for the suggestion. We'll go with #1024, since this is more PeterPortal's realm of functionality. I suggest you use it for these tasks (e.g., 4-year planning and class history).
