### ISSUE TITLE
Underscore for Tab Doesn't Resize On Adjusting the Panes

### ISSUE THREAD

**Issue by adcockdalton** [icssc/AntAlmanac#967]
The blue line that highlights what tab you are on does not adjust when you adjust the pane distribution.

Before adjusting the pane (NORMAL)
<img width="960" alt="image" src="https://github.com/icssc/AntAlmanac/assets/105406853/a7e87fd9-eed6-4dca-b7f7-c8b07eb3adc5">

After shrinking the pane (blue line has not changed).
<img width="960" alt="image" src="https://github.com/icssc/AntAlmanac/assets/105406853/4cbdd74d-df9d-4423-899d-2a63910822e9">

**Comment by KevinWu098** [comment]
This might be a compatibility issue with the divider library and MUI -- can't think of a way to programatically alert MUI to an update from divider

**Comment by KevinWu098** [comment]
This is resolved... somehow...

![chrome-capture-2024-10-21](https://github.com/user-attachments/assets/565479a0-a2aa-48da-ae4f-b8a84e63f0d7)

**Comment by KevinWu098** [comment]
This is resolved... somehow...

![chrome-capture-2024-10-21](https://github.com/user-attachments/assets/565479a0-a2aa-48da-ae4f-b8a84e63f0d7)
