### ISSUE TITLE
Christmas Logo in mid-Spring

### ISSUE THREAD

**Issue by adcockdalton** [icssc/AntAlmanac#969]
Not to be a scrooge, and this is just a nitpick, but the logos are still the Christmas versions.

Should be a simple change to the default, but I'm also curious if we had a spring design? I don't see it in assets. Did we have a designer for that, and can we ask them for a spring version? Just thinking out loud here.

**Comment by MinhxNguyen7** [comment]
We should switch the logo back to normal until there's some sort of event. The logos are designed by someone external

**Comment by adcockdalton** [comment]
Okay, I wonder if we can get a defined set of custom logos and timeframes and just write up logic to switch it based on datetime

For the meantime I'll change the logo back, but I'll put up an issue for doing it dynamically and assign it to myself to do, but we'd probably want minimally a logo for spring and a logo for summer if we're employing christmas (winter) and thanksgiving (fall) specialty logos. Then the logic can minimally partition by season which makes this fun (albeit frivolous) thing more consistent.
