### ISSUE TITLE
Migrate to RDS

### ISSUE THREAD

**Issue by MinhxNguyen7** [icssc/AntAlmanac#970]
## Description
- Migrate the DB from Dynamo to RDS.
- Even though we could make auth work with NoSQL, attaching the notifications system onto it would just not make sense.
- Alternatively, we can make the notification separate from the auth system, and people just sign up for notifications on a per-email/phone number basis.

### Migration Procedures
- [x] Start saving to both DBs. #993 #1064 #1065 #1066 
- [ ] Copy to new DB, while still writing to both. (IN PROGRESS)
    - This needs to be done while few people are using AA. I can set up a chron job to do this at an ungodly hour.
    - Then I'll check in the morning to see if it worked. 
    - Scheduled for 1:40 AM PT, December 6th.
- [ ] Switch read to new DB. #1060 
- [ ] Remove old DB.

**Comment by MinhxNguyen7** [comment]
@ap0nia What do you think? It would make more sense, but we'd have to throw away the work we put in to keeping Dynamo (which is sunk cost, yes).

**Comment by ap0nia** [comment]
Idea: create a script that populates the postgres database on RDS with entries from the DynamoDB.
