### ISSUE TITLE
RateMyProfessor hyperlink broken

### ISSUE THREAD

**Issue by JackyZzZz** [icssc/AntAlmanac#975]
It seems like all the hyperlinks for ratemyprofessor are broken... They link to a page with Internal Server Error, but the site is functioning. It looks the way they structure the search using URL might've changed.

**Comment by MinhxNguyen7** [comment]
They did change the URL structure, and professors just have numbers now. We can only link to a search. See #594.

The only thing we can do to bring back the functionality is for PPAPI to scrape RMP for the professor ID for each professor and give it to us, but that's probably not worth it.
